baseURL = "/"
languageCode = "fr-fr"
summaryLength = "10"
theme = "qori"
title = "Qori"

[menu]
[[menu.main]]
URL = "about"
name = "Quiénes somos?"
weight = 1

[[menu.main]]
identifier = "estudia"
URL = "estudia"
name = "Estudia en Francia"
weight = 2
[[menu.main]]
parent = "estudia"
URL = "estudia/frances"
name = "Francés"
weight = 1
[[menu.main]]
parent = "estudia"
URL = "estudia/carrera_universitaria"
name = "Carrera Universitaria"
weight = 2

[[menu.main]]
identifier = "traduccion"
URL = "traduccion"
name = "Traducción e Interpretación"
weight = 4
[[menu.main]]
parent = "traduccion"
URL = "traduccion/comercial"
name = "Comercial"
weight = 1
[[menu.main]]
parent = "traduccion"
URL = "traduccion/informatica"
name = "Informática"
weight = 2
[[menu.main]]
parent = "traduccion"
URL = "traduccion/literaria"
name = "Literaria"
weight = 3
[[menu.main]]
parent = "traduccion"
URL = "traduccion/relectura"
name = "Relectura"
weight = 4
[[menu.main]]
parent = "traduccion"
URL = "traduccion/simple"
name = "Simple"
weight = 5

[[menu.main]]
identifier = "interpretacion"
URL = "interpretacion"
name = "Interpretación"
weight = 5
[[menu.main]]
parent = "interpretacion"
URL = "interpretacion/simultanea"
name = "Simultánea"
weight = 1
[[menu.main]]
parent = "interpretacion"
URL = "interpretacion/consecutiva"
name = "Consecutiva"
weight = 2

[[menu.main]]
identifier = "asesorias"
URL = "asesorias"
name = "Asesorias"
weight = 6
[[menu.main]]
parent = "asesorias"
URL = "asesorias/empleo"
name = "Búsqueda de empleo en Francia"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 7

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 8

[params]
author = "Ana Medina"
copyright = "Qori - Copyright &copy; 2020"
description = "Qori est une société proposant des services à vos besoins"
email = "anamedina111@gmail.com"
#google_analitycs_id = "Your ID"
home = "Qori"
logo = "images/logo-w-sm.gif"
phone = "+33 6 .. .. .. .."

primary_color = "#cf1931"
nav_color = "#102f5e"

[params.contact]
enable = false
form_action = "#"

[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"

[params.preloader]
enable = true
preloader = "Welcome! Qori"

[[params.social]]
URL = "#"
icon = "ti-facebook"
